# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.17.2
loom_version=1.13.6
# Mod Properties
mod_version=0.1.5a-indev
maven_group=net.capozi
archives_base_name=limbo-express
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.116.9+1.21.1
datasync_version = 0.9.0
mod_menu_version = 11.0.3
ratatouille_version=1.4.3-1.21.1
cca_version=6.1.1
midnightlib_version = 1.5.7-fabric
voicechat_api_version=2.6.0
voicechat_version=1.21.1-2.6.4
sodium_version=mc1.21.1-0.6.13
iris_version=1.8.8+1.21.1
jcpp_version= 1.4.14
glslTransformer_version= 3.0.0-pre3
dotzip_version=1.2.2.2a-1.21.1